name_expr: |
    import re
    normalize = lambda x: re.sub(r'\W+', '_', x).strip('_')
    return normalize(self['name'])

children:
    Asset: Asset.yml
    Sequence: Sequence.yml

templates:

    # These are explicitly handed a PublishEvent, Step, and Version
    # They are expected to return the path without extension.
    plate_publish_dailies:             "VFX_Dailies/{now:%Y-%m-%d}/{publisher.link[step][code]}/{publisher.review_version_entity[id]}_{publisher.name}_v{publisher.version:04d}{ext}"
    reference_footage_publish_dailies: "VFX_Dailies/{now:%Y-%m-%d}/{publisher.link[step][code]}/reference_footage/{publisher.review_version_entity[id]}_{publisher.name}_v{publisher.version:04d}{ext}"
